function[distance] =  computing_distance(centroid, area)
% computing the distance from the centroid to the first edge of the area
       distance = ...
           abs(det([(area(1,1) - area(2,1)) ,(area(1,2) - area(2,2)); ...
                    (centroid(1) - area(2,1)), (centroid(2) - area(2,2))] ) / ...
                     norm(area(1,:) - area(2,:)));
end