function[verticesInProjectedArea, lastVertexInside, penultimateVertexInside] = ...
    vertices_inside_projected_areas(lastVertex, penultimateVertex, line, ...
                                    projectedAreaX, projectedAreaY, ...
                                    verticesInProjectedArea, ...
                                    lastVertexInside, penultimateVertexInside)
    % verifying if the last and penultimate lowerVertices are
    % inside the projected areas of the first line
 
    if(line == 1 && ~lastVertexInside && ...
       inpolygon(lastVertex(1), lastVertex(2), ...
                 projectedAreaX(1,:), projectedAreaY(1,:)))
       verticesInProjectedArea = verticesInProjectedArea + 1; 
       lastVertexInside = true;
    end

    if(line == 1 && ~penultimateVertexInside && ... 
       inpolygon(penultimateVertex(1), penultimateVertex(2), ...
                 projectedAreaX(1,:), projectedAreaY(1,:)))
       verticesInProjectedArea = verticesInProjectedArea + 1;
       penultimateVertexInside = true;
    end
end